
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.VBox mainVBox;

	private global::Gtk.MenuBar mainMenuBar;

	private global::Gtk.Toolbar mainToolbar;

	private global::Gtk.VPaned vpaneMain;

	private global::Gtk.HPaned hpaneContent;

	private global::Gtk.Frame frameTree;

	private global::Gtk.Alignment alignmentProjects;

	private global::Gtk.ScrolledWindow scrolledWindowProjects;

	private global::Gtk.TreeView treeViewProjects;

	private global::Gtk.Label labelProjects;

	private global::Gtk.Frame frameProperties;

	private global::Gtk.Alignment alignmentProperties;

	private global::Gtk.Label labelProperties;

	private global::Gtk.Statusbar mainStatusBar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("_Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Edit");
		w1.Add(this.EditAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("_View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_View");
		w1.Add(this.ViewAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Help");
		w1.Add(this.HelpAction, null);
		this.newAction = new global::Gtk.Action("newAction", null, null, "gtk-new");
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", null, null, "gtk-open");
		w1.Add(this.openAction, null);
		this.saveAction = new global::Gtk.Action("saveAction", null, null, "gtk-save");
		w1.Add(this.saveAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVBox = new global::Gtk.VBox();
		this.mainVBox.Name = "mainVBox";
		this.mainVBox.Spacing = 6;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'mainMenuBar\'><menu name=\'FileAction\' action=\'FileAction\'/><men" +
				"u name=\'EditAction\' action=\'EditAction\'/><menu name=\'ViewAction\' action=\'ViewAct" +
				"ion\'/><menu name=\'HelpAction\' action=\'HelpAction\'/></menubar></ui>");
		this.mainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/mainMenuBar")));
		this.mainMenuBar.Name = "mainMenuBar";
		this.mainVBox.Add(this.mainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.mainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'mainToolbar\'><toolitem name=\'newAction\' action=\'newAction\'/><t" +
				"oolitem name=\'openAction\' action=\'openAction\'/><toolitem name=\'saveAction\' actio" +
				"n=\'saveAction\'/></toolbar></ui>");
		this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/mainToolbar")));
		this.mainToolbar.Name = "mainToolbar";
		this.mainToolbar.ShowArrow = false;
		this.mainVBox.Add(this.mainToolbar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.mainToolbar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.vpaneMain = new global::Gtk.VPaned();
		this.vpaneMain.CanFocus = true;
		this.vpaneMain.Name = "vpaneMain";
		// Container child vpaneMain.Gtk.Paned+PanedChild
		this.hpaneContent = new global::Gtk.HPaned();
		this.hpaneContent.CanFocus = true;
		this.hpaneContent.Name = "hpaneContent";
		this.hpaneContent.Position = 535;
		// Container child hpaneContent.Gtk.Paned+PanedChild
		this.frameTree = new global::Gtk.Frame();
		this.frameTree.Name = "frameTree";
		this.frameTree.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frameTree.LabelXalign = 0.01F;
		this.frameTree.BorderWidth = ((uint)(2));
		// Container child frameTree.Gtk.Container+ContainerChild
		this.alignmentProjects = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.alignmentProjects.Name = "alignmentProjects";
		// Container child alignmentProjects.Gtk.Container+ContainerChild
		this.scrolledWindowProjects = new global::Gtk.ScrolledWindow();
		this.scrolledWindowProjects.Name = "scrolledWindowProjects";
		// Container child scrolledWindowProjects.Gtk.Container+ContainerChild
		this.treeViewProjects = new global::Gtk.TreeView();
		this.treeViewProjects.CanFocus = true;
		this.treeViewProjects.Name = "treeViewProjects";
		this.scrolledWindowProjects.Add(this.treeViewProjects);
		this.alignmentProjects.Add(this.scrolledWindowProjects);
		this.frameTree.Add(this.alignmentProjects);
		this.labelProjects = new global::Gtk.Label();
		this.labelProjects.Name = "labelProjects";
		this.labelProjects.Xalign = 1F;
		this.labelProjects.Yalign = 1F;
		this.labelProjects.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Projects</b>");
		this.labelProjects.UseMarkup = true;
		this.frameTree.LabelWidget = this.labelProjects;
		this.hpaneContent.Add(this.frameTree);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.hpaneContent[this.frameTree]));
		w7.Resize = false;
		// Container child hpaneContent.Gtk.Paned+PanedChild
		this.frameProperties = new global::Gtk.Frame();
		this.frameProperties.Name = "frameProperties";
		this.frameProperties.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frameProperties.Gtk.Container+ContainerChild
		this.alignmentProperties = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.alignmentProperties.Name = "alignmentProperties";
		this.alignmentProperties.BorderWidth = ((uint)(5));
		this.frameProperties.Add(this.alignmentProperties);
		this.labelProperties = new global::Gtk.Label();
		this.labelProperties.Name = "labelProperties";
		this.labelProperties.Xalign = 1F;
		this.labelProperties.Yalign = 1F;
		this.labelProperties.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Properties</b>");
		this.labelProperties.UseMarkup = true;
		this.frameProperties.LabelWidget = this.labelProperties;
		this.hpaneContent.Add(this.frameProperties);
		this.vpaneMain.Add(this.hpaneContent);
		this.mainVBox.Add(this.vpaneMain);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.vpaneMain]));
		w11.Position = 2;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.mainStatusBar = new global::Gtk.Statusbar();
		this.mainStatusBar.Name = "mainStatusBar";
		this.mainStatusBar.Spacing = 6;
		this.mainVBox.Add(this.mainStatusBar);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.mainVBox[this.mainStatusBar]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.mainVBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1121;
		this.DefaultHeight = 734;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
